### ISSUE TITLE
Название предметов

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#13]
Надо наверное посмотреть название предметов. Что бы было единообразие с Готика 2 НВ.

Кирка тоже как то странно называется.. 

Можно сюда закинуть список предметов из файлов Готика 2 классик и Готика 2 НВ?

**Comment by dosinabox** [comment]
> Можно сюда закинуть список предметов из файлов Готика 2 классик и Готика 2 НВ?

Слишком много, так что нет.

**Comment by dosinabox** [comment]
> Кирка тоже как то странно называется..

Очень смешно) Переименована в кирку.

> Надо наверное посмотреть название предметов. Что бы было единообразие с Готика 2 НВ.

Пытаюсь по возможности. То же самое с моделями.

**Comment by Kor-Angar** [comment]
"Скелеты-войны" называются просто "скелетами"

**Comment by dosinabox** [comment]
> "Скелеты-войны" называются просто "скелетами"

Переименованы:
скелет - скелет-воин
малый скелет - скелет

**Comment by dosinabox** [comment]
В Г2 посох судьи - одноручный)

**Comment by dosinabox** [comment]
Похоже, что сейчас всё в порядке.
