### ISSUE TITLE
Озвучка

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#15]
пропала фраза "Эй ты" когда герой обращается к НПС

**Comment by dosinabox** [comment]
Покажи что у тебя в папках  Gothic II/Data.

**Comment by Kor-Angar** [comment]
овца еще не говорила "ме" в ответ герою который ей говорил пошли со мной

**Comment by Kor-Angar** [comment]
не играла музыка при повышение уровня

**Comment by dosinabox** [comment]
> овца еще не говорила "ме" в ответ герою который ей говорил пошли со мной

Исправлено.

> не играла музыка при повышение уровня

У меня играет. А у тебя никогда не играла или только единично?

**Comment by dosinabox** [comment]
А в чистом оригинале 1.3 есть файл Data/speech3.vdf?

**Comment by Kor-Angar** [comment]
в диалоге с Абуином герой не говорит "Я готов"

https://youtu.be/ACvzRz1BUmg?t=3146

**Comment by dosinabox** [comment]
Не озвучена, но и озвучить её в этом диалоге не получится - анимация всегда перекрывает разговоры. Техническая особенность.
То же самое - перед видеороликом в диалоге с Сатурасом о событиях в Новом Лагере из Г1, а также в диалогах с капитанами, которые завершают игру.
