### ISSUE TITLE
Огненное дыхание драконов

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2_classic#16]
Нужно проверить, наносят ли драконы правильный и адекватный урон по ГГ в ближнем бою. По возможности сравнить с оригиналом 1.3 на персонаже с аналогичной защитой и здоровьем.

**Comment by dosinabox** [comment]
Проверено на pc_itemfeller (400 здоровья, 50 защиты от огня) и Финкреге.
мод g2_classic D36: -150
мод-фикс Desomorphine: -70
оригинал 1.3: ?

![1](https://user-images.githubusercontent.com/39790055/64920947-dd217f80-d7c5-11e9-8641-36ee35523535.jpg)
![2](https://user-images.githubusercontent.com/39790055/64920948-dd217f80-d7c5-11e9-8155-526be5081930.jpg)

**Comment by Kor-Angar** [comment]
версия 1,30 защита от огня не влияет на ущерб получаемый  Драконов. он статичен у Огненного Дракона 13, у Каменного Дракона 12.

потом герой получает ещё ущерб от падения, а потом ущерб от фаербола(магический урон).

**Comment by Kor-Angar** [comment]
в твоей версии защита от огня так же не влияет на ущерб
огненный дракон 140
каменный дракон 130

**Comment by Kor-Angar** [comment]
> версия 1,30 защита от огня не влияет на ущерб получаемый Драконов. он статичен у Огненного Дракона 13, у Каменного Дракона 12.

систем пак на это не может влиять?

**Comment by Kor-Angar** [comment]
проверил мод g2_classic D36 и мод-фикс Desomorphine. ущерб одинаковый. перепроверь плиз внимательно.

Защита огня на него не влияет(думаю это ключевое открытие для всех:-) ).

- каменный дракон наносит 130 (у него 130 "силы")
- огненный дракон наносит 140 (у него 140 "силы")

отредактировал Огненном дракону "силу" до 300, ущерб поднялся до 300.

> потом герой получает ещё ущерб от падения, а потом ущерб от фаербола(магический урон).

ущерб от фаербола равен 60, урон магией, зависит от защиты от магии

**Comment by Kor-Angar** [comment]
может я скачал не ту версию мод-фикс Desomorphine? :-))

> - Драконы вместо «Огненного шара» теперь используют «Стрелу смерти». 
> 
> - Драконы перестали отбрасывать при атаке. Исправлена недоработка, из-за которой у них не был задействован огненный урон в ближнем бою. 
> 
> - Усилены драконы (увеличено количество здоровья, а также урон от огня).

**Comment by Kor-Angar** [comment]
> может я скачал не ту версию мод-фикс Desomorphine? :-))
твой файл "g2classic_russian" перебивает мод-фикс? ;-)

**Comment by dosinabox** [comment]
> твой файл "g2classic_russian" перебивает мод-фикс? ;-)

Конечно. Все vdf в приоритете над mod.

**Comment by dosinabox** [comment]
> систем пак на это не может влиять?

Нет.

**Comment by dosinabox** [comment]
Это движок 1.3 так обрабатывает отбрасывающий урон DAM_FLY. Видимо, сила делится на 10. А в 2.6 не делится, при этом тип урона изменен на огненный DAM_FIRE (в комбинации с отбрасывающим).

**Comment by Kor-Angar** [comment]
тогда вытекают два вопроса:

- [ ] защита от огня героя учитывалась при расчёте урона
- [ ] что бы герой догорал, как от огненной ящерицы

**Comment by dosinabox** [comment]
Будет точно как в оригинале. Без учета защиты от огня и без догорания. Для вольностей есть мод-фикс от Desomorphine.

**Comment by Kor-Angar** [comment]
> Будет точно как в оригинале. Без учета защиты от огня и без догорания.
а урон какой будет? :-)

**Comment by dosinabox** [comment]
> а урон какой будет? :-)

У Финкрега - 14 (без учета урона при падении - там зависит от расстояния полета).
У остальных сегодня посмотрю в игре.

**Comment by Kor-Angar** [comment]
ну это явная  какая то ошибка. хз чем вызванная. не мог у них быть такой низкий урон это бы обязательно заметили и сто раз перетёрли на форуме :)

может универсальный патч пираний сломал все это дело как то? попробую запустить пиратку 1,28 и посмотреть что было там

**Comment by dosinabox** [comment]
Точные данные:

Болотный - 11
Каменный - 12
Огненные - 13
Ледяной - 14
Нежить - 16

> не мог у них быть такой низкий урон это бы обязательно заметили и сто раз перетёрли на форуме :)

Дело же не в уроне, а в том, что он ничем не блокируется. Плюс сразу за ним следует полет и урон от падения, а потом ещё и пара фаерболов в лицо. Урон низкий, но он нужен только чтобы выключить ГГ из боя и отбросить его подальше. Этакий стан.
Перепроверь сам) Подойди вплотную с полным хп, дай себя отбросить и в этот момент смотри статы. Мои - на скриншоте выше.

**Comment by dosinabox** [comment]
Есть же минимальный урон 5, который всегда проходит через любую защиту, благодаря чему ГГ нулевого уровня может запинать черного тролля кулаком. Вот и у драконов есть такая же защита от ГГ. Минимальный гарантированный урон для ближнего боя, повышенный в 2-3 раза.
Кстати, в 1.3 есть этот минимальный урон 5?

**Comment by Kor-Angar** [comment]
> Перепроверь сам) Подойди вплотную с полным хп, дай себя отбросить и в этот момент смотри статы (до касания земли)

так я так и делал :-) 

> версия 1,30 защита от огня не влияет на ущерб получаемый Драконов. он статичен у Огненного Дракона 13, у Каменного Дракона 12.
> потом герой получает ещё ущерб от падения, а потом ущерб от фаербола(магический урон).

проверил в 1.28 всё так же. вспомнил что драконы вообще тупили и боком пытались уйти в никуда. вот это и обсуждали на форумах :-))

> Дело же не в уроне, а в том, что он ничем не блокируется. Плюс сразу за ним следует полет и урон от падения, а потом ещё и пара фаерболов в лицо. Урон низкий, но он нужен только чтобы выключить ГГ из боя и отбросить его подальше. Этакий стан.

видимо так и было задумано. особенно прочувствует ОНД так как у его доспехов минимальная защита от магии. Магу же наоборот будет всё равно так как он может иметь защиту от магии выше чем урон от Фаербола.

**Comment by dosinabox** [comment]
Готово, теперь будет точно как в оригинале 1.3.

**Comment by Kor-Angar** [comment]
валяющийся герой после удара неотлетает.  вчера и так и эдак тестил драконов :-) вроде не тупят но мне показалось что агрессивности им не хватает. в аддоне они как то более агрессивны. а тут могут перестать атаковать героя :-(
https://www.youtube.com/watch?v=6fRvUmQJtog
