### ISSUE TITLE
Mod версия

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#19]
Надо G2 classic  в виде мод версии. он уже влияет на неофициальное обновление г2НВ
![image](https://user-images.githubusercontent.com/49514764/64930129-5658bb00-d836-11e9-822e-044589561f39.png)
Ягода Гоблина появилась из G2 classic в неофициальном обновлении для Г2НВ

**Comment by dosinabox** [comment]
> Надо G2 classic в виде мод версии

Будет. Сейчас просто для тестов.

> Ягода Гоблина появилась из G2 classic в неофициальном обновлении для Г2НВ

Это где?

**Comment by Kor-Angar** [comment]
Это из-за файла Готики 2 классик она появилась. Если файл удалить то все будет Ок.

**Comment by dosinabox** [comment]
Смотри только сохранения не делай на такой солянке, а то проблемы будут.
А где появилась? На скрине не видно. В классике где-то появляется ягода, а в НВ нет?

**Comment by Kor-Angar** [comment]
в мире "миненталь" Готике 2 класик   много растений(ягоды гоблина, драконий корень, царский щавель). в НВ эти растения поубирали.

**Comment by dosinabox** [comment]
> в мире "миненталь" Готике 2 класик много растений(ягоды гоблина, драконий корень, царский щавель). в НВ эти растения поубирали.

Мир из классики заменил миры неофициального обновления. Если ты сохранился, то этот мир останется в сохраненке.

**Comment by dosinabox** [comment]
Как назовем мод?)

**Comment by Kor-Angar** [comment]
Gothic 2 v.1.30 :-) или Gothic 2 classic или ещё как то :-D

**Comment by Kor-Angar** [comment]
или  Gothic 2 classic [без аддона] ;-)

**Comment by Kor-Angar** [comment]
так так, а когда будет мод версия? :-)

**Comment by dosinabox** [comment]
могу быстро собрать, если нужно

**Comment by Kor-Angar** [comment]
так надо сделать что бы была ;-) тогда её можно будет продолжить тестировать;-)

**Comment by dosinabox** [comment]
а что, есть планы продолжить в ближайшее время?)

**Comment by Kor-Angar** [comment]
я бы за мага сыграл. в Готике 2 НВ у Мага в плане баланса все плохо. а в Готике 2 оригинал Маг был весьма бодрый. поэтому пройти оригинал за мага было бы полезно сразу и для Г2НВ (в сравнение станет понятно гдеперекос произошёл) и для Г2Ор.

**Comment by dosinabox** [comment]
тогда на днях обновлю до 0.8

**Comment by Kor-Angar** [comment]
спасибо25.10.2019, 14:35, "dosinabox" <notifications@github.com>:тогда на днях обновлю до 0.8

**Comment by dosinabox** [comment]
готово
