### ISSUE TITLE
Тестовый Амулет g2_classic

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#2]
а можно добавить в эту сборку тестовый амулет?

**Comment by dosinabox** [comment]
Можно, принято.

**Comment by Kor-Angar** [comment]
спс

**Comment by Kor-Angar** [comment]
надо по коду тестого амулета вставлять книгу :-) а то только за год один код выучат граждане а Дося уже коды поменяла :-)

**Comment by Kor-Angar** [comment]
явки и пароли :-)
