### ISSUE TITLE
Скачать g2_classic

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#22]
Запости сюда плиз ссылки на темы о моде g2_classic на WoP, RPG и Steam.

https://github.com/dosinabox/g2_classic/releases

**Comment by dosinabox** [comment]
Ты про что? Он пока размещен только в стиме, да и то без объявлений и названий:
https://steamcommunity.com/sharedfiles/filedetails/?id=787949644
Больше нигде его нет.

**Comment by dosinabox** [comment]
Ну, и напоминаю, что у мода до сих пор нет названия)

**Comment by Kor-Angar** [comment]
Надо уже как то назвать😀.Хочу пройти как и планировал за Мага. Поэтому надо дать ссылку на скачивание, так как люди интересуются в личку пишут, спрашивают 😀

**Comment by dosinabox** [comment]
Если нужно давать ссылку, то пока давай сюда:
https://github.com/dosinabox/g2_classic/releases
А нам точно нужны прошлые версии? Можно немного допилить 0.9, а все остальные удалить. Здесь в кодовой базе все итерации скриптов есть, можно любую версию собрать когда захочется.

Надо будет заняться каким-никаким "продвижением" - оформить описание, выложить где-нибудь, рассказать народу. Название всё же есть - "Готика II - Классическая". Но это просто чтобы в стартере были красиво:
```
Готика II - Ночь Ворона
Готика II - Классическая
```
Так можно и  оставить)
