### ISSUE TITLE
Русификация SH и CH

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#23]
Можно будет русифицировать помощников по сюжету и хар-кам

![image](https://user-images.githubusercontent.com/49514764/69079563-4da97e80-0a4b-11ea-8e1a-ddaba420de2e.png)

**Comment by dosinabox** [comment]
и FH)

**Comment by Kor-Angar** [comment]
а "FH" это кто? :-)

**Comment by dosinabox** [comment]
> а "FH" это кто? :-)

Помощник по лицам - для подбора тел, голов и лиц персонажам.

**Comment by dosinabox** [comment]
собственно, готово
