### ISSUE TITLE
Кольцо предводителя орков

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#24]
если герой который имеет 10 силы оденет кольцо предводителя орков(-20 силы), то после того как он его снимет у героя станет 20 силы

**Comment by dosinabox** [comment]
Что ты предлагаешь?
Нужно ли нам исправлять "позитивные" баги в рамках этого проекта?

**Comment by Kor-Angar** [comment]
Какие то явные баги конечно стоит исправить, но  увлекаться этим делом нельзя 😀

**Comment by dosinabox** [comment]
пока отложим вопрос
