### ISSUE TITLE
Файлы игры

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#26]
> Поделись файлом gothic.dat - буду смотреть, откуда тогда взялось 600 опыта в моих декомпилированных скриптах.

вот тут по ссылке в папке G2_or_de
https://yadi.sk/d/2nBogZV8FLYx4Q

**Comment by Kor-Angar** [comment]
потерял кнопку "закрепить" :-)

**Comment by dosinabox** [comment]
справа - Pin issue

**Comment by dosinabox** [comment]
Есть ли разница между Миненталем оригинала и аддона? За исключением табличек, которые вставляются в мир скриптом.

**Comment by Kor-Angar** [comment]
Мне кажется есть. Пытаюсь найти в чем, а найти не могу. Посмотри на зелье силы которое вставлено в пещере со склетом мракориса. Мне казалось что оно был но в другом месте. 20:22, 11 июля 2020 г., dosinabox <notifications@github.com>:
Есть ли разница между Миненталем оригинала и аддона? За исключением табличек, которые вставляются в мир скриптом.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
Вспомнился алтарь Белиара в аддоне. А значит мир оригинала всё-таки нужно добавлять в мод.

**Comment by Kor-Angar** [comment]
> Вспомнился алтарь Белиара в аддоне. А значит мир оригинала всё-таки нужно добавлять в мод.

а файлы мира по размеру не совпадают ?

**Comment by dosinabox** [comment]
> а файлы мира по размеру не совпадают ?

В аддоне больше на примерно 200 кб.

**Comment by Kor-Angar** [comment]
Надо тестить. Проверить в первую очень перманентные растения (их в классике много) , потом эликсиры, потому шмотки. 17:48, 12 июля 2020 г., dosinabox <notifications@github.com>:

а файлы мира по размеру не совпадают ?

В аддоне больше на примерно 200 кб.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
У меня кстати игра вылетала один раз в Минентале, там где эликсир силы лежит17:48, 12 июля 2020 г., dosinabox <notifications@github.com>:

а файлы мира по размеру не совпадают ?

В аддоне больше на примерно 200 кб.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> Надо тестить. Проверить в первую очень перманентные растения (их в классике много) , потом эликсиры, потому шмотки. 

Это неважно, потому что я в любом случае буду включать в мод мир оригинала.

**Comment by Kor-Angar** [comment]
Это было бы не важно если бы скрипты были оригинальные немецкие ;-) 20:05, 12 июля 2020 г., dosinabox <notifications@github.com>:

Надо тестить. Проверить в первую очень перманентные растения (их в классике много) , потом эликсиры, потому шмотки. 

Это неважно, потому что я в любом случае буду включать в мод мир оригинала.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
А у тебя есть GOTHIC.DAT от английской 1.30?

**Comment by Kor-Angar** [comment]
Наверное ты про 1,31 😀Английская и русская 1,31Немецкая 1,30.Поищу.16:59, 22 февраля 2021 г., dosinabox <notifications@github.com>:
А у тебя есть GOTHIC.DAT от английской 1.30?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
Немецкая 1,29
[exe_Gothic2_1_29_de.zip](https://github.com/dosinabox/g2_classic/files/6024387/exe_Gothic2_1_29_de.zip)
[Gothic2_1_29_de.zip](https://github.com/dosinabox/g2_classic/files/6024390/Gothic2_1_29_de.zip)

Немецкая 1,30
[Gothic2_1_29_de.zip](https://github.com/dosinabox/g2_classic/files/6024399/Gothic2_1_29_de.zip)
[exe_Gothic2_1_30_de.zip](https://github.com/dosinabox/g2_classic/files/6024389/exe_Gothic2_1_30_de.zip)
[Gothic2_1_30_de.zip](https://github.com/dosinabox/g2_classic/files/6024403/Gothic2_1_30_de.zip)
[Gothic2_1_30_de.zip](https://github.com/dosinabox/g2_classic/files/6024391/Gothic2_1_30_de.zip)

**Comment by dosinabox** [comment]
Английская 1.31 сойдет, если есть.

**Comment by Kor-Angar** [comment]
Пока ищу22:25, 22 февраля 2021 г., dosinabox <notifications@github.com>:
Английская 1.31 сойдет, если есть.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/108766392-2a328500-7566-11eb-8068-dbf3d03d9485.png)
а как такую подсветку сделать в Notepad++ ?:-)

**Comment by dosinabox** [comment]
https://worldofplayers.ru/threads/41093/

**Comment by Kor-Angar** [comment]
не могу найти 1,31 вроде тут должен был лежать http://www.bendlins.de/nico/

но в веб архиве записей нет.

в целом 1,31 патч отличается от 1,30 только языком.
