### ISSUE TITLE
Лотар не идёт в вверхний квартал

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#27]
Лотар не уходит в вверхний квартал. или это уже добавили в НВ?

**Comment by dosinabox** [comment]
И там и там должен уходить, если расказал о новых правилах. У тебя рассказал или ГГ говорит "позже" при завершении диалога?

**Comment by Kor-Angar** [comment]
Я правила не слушал, что бы он остался внизу и не ушёл в верхний квартал.Но он так же уходит когда герой получает доступ в верхний квартал. Т. Е. это вступлению в гильдию или если герой стал подмостерье. По крайней мере так у тебя в неофициально обновление, мы это обсуждали

**Comment by dosinabox** [comment]
> Но он так же уходит когда герой получает доступ в верхний квартал. Т. Е. это вступлению в гильдию или если герой стал подмостерье

это появилось только в аддоне
