### ISSUE TITLE
диалоги про "Глаз Инноса"

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#31]
Диалоги про то что Глаз Инноса разрушен с Пирокаром и Ватрасом доступен до того как герой найдёт сам глаз Инноса. т.е. он становится доступен после разговора с Ищущим возле круга Солнца

**Comment by dosinabox** [comment]
Не баг, потому что о разрушении Глаза говорит сам Ищущий около места ритуала:
```
AI_Output(self,other,"DIA_RitualDementor_19_00");	//Ты пришел слишком поздно.
AI_Output(self,other,"DIA_RitualDementor_19_01");	//Мы уничтожили Глаз Инноса, и теперь ему никогда не вернуть былую силу.
AI_Output(self,other,"DIA_RitualDementor_19_02");	//Теперь мы продемонстрируем всю тщетность твоих попыток бросить вызов Хозяину.
```

**Comment by Kor-Angar** [comment]
Да. Но разве герой не должен взять глаз Инноса что бы был доступен диалог с Пирокаром/Ксардасом/Ватрасом о том что герой нашёл глаз Инноса и он разрушен?

**Comment by dosinabox** [comment]
Диалог с Пирокаром:
```
AI_Output(other,self,"DIA_Pyrokar_FOUNDINNOSEYE_15_00");	//Я нашел Глаз Инноса. Он поврежден.
```

Диалог с Ватрасом:
```
AI_Output(other,self,"DIA_Vatras_INNOSEYEKAPUTT_15_02");	//Глаз Инноса поврежден.
```

ГГ не скажет Пирокару "Я нашел Глаз Инноса", если у него нет Глаза в инвентаре - в этом случае будет воспроизводиться реплика из диалога с Ватрасом. То же самое в Г2НВ.

**Comment by Kor-Angar** [comment]
Это значит что не имея глаза можно поговорить с Ватрасом и он отправит ГГ ченить глаз?

**Comment by dosinabox** [comment]
такие вот условности...
