### ISSUE TITLE
Джора диалог про Меч Альрика

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#32]
у Джоры не было диалога про меч Альрика

**Comment by dosinabox** [comment]
Этот?
```cpp
instance DIA_JORA_ALRIKSSCHWERT(C_INFO)
{
	npc = vlk_408_jora;
	nr = 1;
	condition = dia_jora_alriksschwert_condition;
	information = dia_jora_alriksschwert_info;
	permanent = FALSE;
	description = "Альрик говорит, что у тебя его меч...";
};


func int dia_jora_alriksschwert_condition()
{
	if(MIS_ALRIK_SWORD == LOG_RUNNING)
	{
		return TRUE;
	};
};

func void dia_jora_alriksschwert_info()
{
	AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_00");	//Альрик говорит, что у тебя его меч...
	AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_01");	//Ты имеешь в виду этого оборванца, что продал мне свое оружие за несколько факелов и кусок мяса?
	AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_02");	//Да, это он.
	if(Npc_HasItems(self,itmw_alrikssword_mis) > 0)
	{
		AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_03");	//Его меч все еще у меня.
		AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_04");	//Сколько ты хочешь за него?
		if(JORA_GOLD == LOG_SUCCESS)
		{
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_05");	//Ну - для тебя...
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_06");	//А, ладно! Забирай его так. Ведь ты помог мне вернуть мое золото...
			b_giveinvitems(self,other,itmw_alrikssword_mis,1);
		}
		else
		{
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_07");	//Ну - только для тебя - 50 золотых монет.
		};
	}
	else
	{
		AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_08");	//(раздраженно) У меня его больше нет! Черт его знает, кому я его продал!
	};
};
```

**Comment by Kor-Angar** [comment]
Я уже не вспомню что там было. Это надо заново ставить и проверять. Скорее всего речь идёт про тот диалог что ты привела. 0:54, 10 января 2021 г., dosinabox <notifications@github.com>:
Этот?
instance DIA_JORA_ALRIKSSCHWERT(C_INFO)
{
	npc = vlk_408_jora;
	nr = 1;
	condition = dia_jora_alriksschwert_condition;
	information = dia_jora_alriksschwert_info;
	permanent = FALSE;
	description = "Альрик говорит, что у тебя его меч...";
};


func int dia_jora_alriksschwert_condition()
{
	if(MIS_ALRIK_SWORD == LOG_RUNNING)
	{
		return TRUE;
	};
};

func void dia_jora_alriksschwert_info()
{
	AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_00");	//Альрик говорит, что у тебя его меч...
	AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_01");	//Ты имеешь в виду этого оборванца, что продал мне свое оружие за несколько факелов и кусок мяса?
	AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_02");	//Да, это он.
	if(Npc_HasItems(self,itmw_alrikssword_mis) > 0)
	{
		AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_03");	//Его меч все еще у меня.
		AI_Output(other,self,"DIA_Jora_AlriksSchwert_15_04");	//Сколько ты хочешь за него?
		if(JORA_GOLD == LOG_SUCCESS)
		{
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_05");	//Ну - для тебя...
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_06");	//А, ладно! Забирай его так. Ведь ты помог мне вернуть мое золото...
			b_giveinvitems(self,other,itmw_alrikssword_mis,1);
		}
		else
		{
			AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_07");	//Ну - только для тебя - 50 золотых монет.
		};
	}
	else
	{
		AI_Output(self,other,"DIA_Jora_AlriksSchwert_08_08");	//(раздраженно) У меня его больше нет! Черт его знает, кому я его продал!
	};
};

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Kor-Angar** [comment]
а Меч Альрика квестовый?

**Comment by dosinabox** [comment]
да

**Comment by Kor-Angar** [comment]
и тут у Меча какая то странная текстура :-(

**Comment by Kor-Angar** [comment]
диалог про меч альрика доступен до того как ГГ побъёт Альрика. я уже запутался. так и должно быть? :-)
![20210302061222_1](https://user-images.githubusercontent.com/49514764/109605777-bd575600-7b36-11eb-8f44-9a3dcc72c6af.jpg)

**Comment by dosinabox** [comment]
> так и должно быть? :-)

да, потому что факт продажи меча упоминается и в другом диалоге:

```cpp
func void DIA_Alrik_DuWohnst_Info()
{
	AI_Output(other,self,"DIA_Alrik_DuWohnst_15_00");	//(удивленно) Ты 'живешь' за этим складом?
	AI_Output(self,other,"DIA_Alrik_DuWohnst_09_01");	//Только временно. (ухмыляется) Когда имеешь столько денег, как у меня, можно позволить себе немного роскоши!
	AI_Output(self,other,"DIA_Alrik_DuWohnst_09_02");	//Я был инструктором в армии, но я бросил это занятие и выбрал судьбу искателя приключений.
	AI_Output(self,other,"DIA_Alrik_DuWohnst_09_03");	//И вот я застрял в этой дыре. Мои последние 100 золотых ушли в карман стражникам у городских ворот.
	AI_Output(self,other,"DIA_Alrik_DuWohnst_09_04");	//И вот я пытаюсь опять разбогатеть. Мне даже пришлось продать свой меч.
	Alrik_VomSchwertErzaehlt = TRUE;
};
```
