### ISSUE TITLE
Горакс ассортимент товаров

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#35]
в 5 главе у Горакса пропал из продажи Огненный Язык и ещё какие то товары. так же пропала "святая вода". и язык и вода и сердца  необходим для изготовления рун.

**Comment by dosinabox** [comment]
Интересно. И в классике, и в аддоне языки варанов считаются "мусором" и удаляются у торговцев с началом следующей главы после появления в продаже. В неофициальном обновлении Г2НВ сделано исключения для Кроноса в Яркендаре и Горакса.

**Comment by Kor-Angar** [comment]
А святая вода? Она была в 4 главе в продаже? Так же мне всегда казалось что святая вода была в склепе, там где Амулет Ангара. В этот раз её там не нашёл. То ли плохо искал, то ли её там не было..

**Comment by dosinabox** [comment]
> Так же мне всегда казалось что святая вода была в склепе, там где Амулет Ангара. В этот раз её там не нашёл. То ли плохо искал, то ли её там не было..

есть:

![20201020154933_1](https://user-images.githubusercontent.com/39790055/96588295-2955c200-12ec-11eb-9cc5-af41f91cf9d9.jpg)

**Comment by Kor-Angar** [comment]
ага. есть

**Comment by dosinabox** [comment]
Пропажа огненного языка у Горакса исправлена. А святая вода должна быть, не вижу ошибок. Ещё она есть у Лютеро и Исгарота.
