### ISSUE TITLE
Руна и Рунический стол

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#36]
если не изготовить руну на руническом столе, то сама руна пропадает.
https://youtu.be/P0vWPcTpFZ0?t=3775

**Comment by dosinabox** [comment]
Такое происходит при неудачной попытке изготовления только двух рун: глыбы льда и уничтожения нежити. Исправлю.

**Comment by Kor-Angar** [comment]
Отлично

**Comment by dosinabox** [comment]
исправлено
