### ISSUE TITLE
Изучение заклинаний паладинов

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2_classic#38]
У Милтена на Ирдорате можно изучить заклинания паладинов. А что дальше? Нигде в коде не вижу, чтобы паладинские руны вообще можно было создать (за исключением телепорта в подвал). В аддоне разработчики написали отдельную функцию **B_TeachPlayerPalRunes**, которая дает ГГ нужную руну в диалогах с Милтеном и Альбрехтом, а в Г2 получается, что обучение у Милтена происходит в пустоту?

**Comment by dosinabox** [comment]
> В аддоне разработчики написали отдельную функцию **B_TeachPlayerPalRunes**, которая дает ГГ нужную руну

Поправка: это появилось только в неофициальном обновлении Г2НВ. Неужели в оригинале Г2НВ обучение у Милтена тоже происходило в никуда? Стало ещё непонятнее.

**Comment by dosinabox** [comment]
> обучение у Милтена происходит в пустоту

исправлено

**Comment by Kor-Angar** [comment]
а в чём суть исправления?
Милтен не учит пала изготовлению рун или Милтен учит? он разве в Готики 2 классик учил?

**Comment by Kor-Angar** [comment]
не учил Милтен Пала. у него же проверка стоит на гильдию

```
	if(hero.guild == GIL_KDF)
	{
		Info_AddChoice(DIA_Milten_DI_TeachMagic,"Создать руну",DIA_Milten_DI_TeachMagic_RUNES);
	};
```

в MDK тоже

```
	if (hero.guild == GIL_KDF)
	{
	Info_AddChoice	  	(DIA_Milten_DI_TeachMagic, 	"Runen herstellen", DIA_Milten_DI_TeachMagic_RUNES);
	};	
```
