### ISSUE TITLE
потрошить животных

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#40]
с Драконов не снимается чешуя и кровь

- Огненный ящер - ок
- Дракон снеппер - ок
- Голем каменный - ок
- Голем огненный -ок
- Демон - ок
- Луркер - ок
- Ящер - ок
- Полевой хищник - ок
- краулер - ок
- краулер воин - ок
- муха - ок
- варг - ок
- волк - ок

**Comment by dosinabox** [comment]
Странно. Чешуя и кровь прописаны только Феодарону и дракону-нежити:
```
if(PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_DRAGONSCALE] == TRUE)
{
	if(Hlp_GetInstanceID(slf) == Hlp_GetInstanceID(firedragonisland))
	{
		CreateInvItems(slf,itat_dragonscale,12);
	};
	if(Hlp_GetInstanceID(slf) == Hlp_GetInstanceID(undeaddragon))
	{
		CreateInvItems(slf,itat_dragonscale,12);
	};
};
```
```
if(PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_DRAGONBLOOD] == TRUE)
{
	if(Hlp_GetInstanceID(slf) == Hlp_GetInstanceID(firedragonisland))
	{
		CreateInvItems(slf,itat_dragonblood,2);
	};
	if(Hlp_GetInstanceID(slf) == Hlp_GetInstanceID(undeaddragon))
	{
		CreateInvItems(slf,itat_dragonblood,2);
	};
};
```
Не ошибка, а вообще не прописано. В классике точно снималась кровь и чешуя? Нужно проверить на чистой 1.3 с дисков.

**Comment by Kor-Angar** [comment]
Смешная шутка 😀 чего проверять то? Без чешуи не сделать средний доспех ОнД, а без крови не выковать мечи ОНД.

**Comment by Kor-Angar** [comment]
а ты откуда эти скрипты Акеллы брала? 
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/B_Story/b_givedeathinv.d#L189

Ну там много чего удивительного можно найти. в таких случаях наверное правильнее всего их сверять с немецкими скриптами. или нет? :-)

**Comment by dosinabox** [comment]
Извиняюсь. Чешуя и кровь создаются у драконов в момент изучения навыков:
```
if(trophy == TROPHY_DRAGONSCALE)
{
	PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_DRAGONSCALE] = TRUE;
	CreateInvItems(swampdragon,itat_dragonscale,12);
	CreateInvItems(rockdragon,itat_dragonscale,12);
	CreateInvItems(firedragon,itat_dragonscale,12);
	CreateInvItems(icedragon,itat_dragonscale,12);
	b_logentry(TOPIC_TALENTANIMALTROPHY,"... снимать чешую с мертвых драконов.");
};
```
```
if(trophy == TROPHY_DRAGONBLOOD)
{
	PLAYER_TALENT_TAKEANIMALTROPHY[TROPHY_DRAGONBLOOD] = TRUE;
	CreateInvItems(swampdragon,itat_dragonblood,2);
	CreateInvItems(rockdragon,itat_dragonblood,2);
	CreateInvItems(firedragon,itat_dragonblood,2);
	CreateInvItems(icedragon,itat_dragonblood,2);
	b_logentry(TOPIC_TALENTANIMALTROPHY,"... собирать кровь из мертвых драконов.");
};
```
Поэтому если изучить эти навыки вне Миненталя (например, у помощника), то чешую и кровь создавать будет не у кого.

**Comment by Kor-Angar** [comment]
я проверял. учил в минентале. не помогло.

**Comment by Kor-Angar** [comment]
> Чешуя и кровь создаются у драконов в момент изучения навыков

это и у мёртвых значит создадутся? :-)

**Comment by Kor-Angar** [comment]
> я проверял. учил в минентале. не помогло.

я когда проверял учил у Гештата. может что то глюкануло. надо будет перепроверить.

**Comment by dosinabox** [comment]
> это и у мёртвых значит создадутся? :-)

Если есть труп (еще из памяти не выгрузился). Как мы выяснили ранее, трупы драконов из мира не пропадают.

**Comment by Kor-Angar** [comment]
ну это же прекрасно:-) и это знак что надо реализовывать вот эту историю

https://github.com/dosinabox/g2nr_unofficial_update/issues/130

**Comment by dosinabox** [comment]
исправлено
