### ISSUE TITLE
помощник по характеристикам

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#41]
не учит 1р до 100

**Comment by Kor-Angar** [comment]
пишет максимум учителя 99

**Comment by Kor-Angar** [comment]
а он акробатике учил? :-)

**Comment by dosinabox** [comment]
> пишет максимум учителя 99

Действительно, 99 максимум. И 1р, и 2р, и лук, и арбалет. Интересно почему. Исправлю на 100.

> а он акробатике учил? :-)

Нет.
