### ISSUE TITLE
Учителя навыков

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#43]
У Удара некорректно отображается цена обучения

![image](https://user-images.githubusercontent.com/49514764/86671594-78f2d500-bffe-11ea-9a68-6c76029eea2a.png)

**Comment by Kor-Angar** [comment]
Для 2р у Паладина  есть DIA_KEROLOTH_TEACH_PERMANENT 
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/Dialoge/DIA_pal_258_keroloth.d#L169

а для 1р нету

мне кажется надо DIA_KEROLOTH_TEACH_PERMANENT переименовать в DIA_KEROLOTH_TEACH_PERMANENT_2H

и добавить ещё DIA_KEROLOTH_TEACH_PERMANENT_1H в коде выше

**Comment by Kor-Angar** [comment]
Для 2р у Паладина  есть DIA_KEROLOTH_TEACH_PERMANENT 
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/Dialoge/DIA_pal_258_keroloth.d#L169

а для 1р нету

мне кажется надо DIA_KEROLOTH_TEACH_PERMANENT переименовать в DIA_KEROLOTH_TEACH_PERMANENT_2H

и добавить ещё DIA_KEROLOTH_TEACH_PERMANENT_1H в коде выше
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/Dialoge/DIA_pal_258_keroloth.d#L96
и сделать проверку на него тут
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/Dialoge/DIA_pal_258_keroloth.d#L99
 
****
а вот тут
https://github.com/dosinabox/g2_classic/blob/b74f16bf512178a743f02ab1eef7ea11c1102a3c/PrjGothic/Story/Dialoge/DIA_pal_258_keroloth.d#L173

условие на  (other.hitchance[NPC_TALENT_2H] < 60 лишнее. если его убрать то Керолт посоветует поискать герою другого учителя и после этого диалог пропадёт.

**Comment by dosinabox** [comment]
> У Удара некорректно отображается цена обучения

исправлено

**Comment by dosinabox** [comment]
c Керолотом тоже готово
