### ISSUE TITLE
Книга статистики

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#47]
если можно как то просто добавить твою книжку из неоф. патча то лучше добавить :-)

**Comment by dosinabox** [comment]
Готово)
![20201227135145_1](https://user-images.githubusercontent.com/39790055/103169295-6342c780-484b-11eb-8764-acdd8ea02286.jpg)

**Comment by dosinabox** [comment]
![20210302061041_1](https://user-images.githubusercontent.com/49514764/109605316-08bd3480-7b36-11eb-94bb-8c6992652558.jpg)
![20210302060942_1](https://user-images.githubusercontent.com/49514764/109605321-0b1f8e80-7b36-11eb-9b0b-9aec45a0067b.jpg)
![20210302060953_1](https://user-images.githubusercontent.com/49514764/109605323-0b1f8e80-7b36-11eb-8795-31973a260fa2.jpg)
![20210302061034_1](https://user-images.githubusercontent.com/49514764/109605324-0bb82500-7b36-11eb-9397-cf04f103d700.jpg)
