### ISSUE TITLE
Очистка вещей у продовца

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#48]
Надо бы сделать очистку книги Лютеро у продавцов при их избиение в случае если герой их прочитал.

или такие правки надо уже делать опционально?

**Comment by dosinabox** [comment]
Разве так не очищаются? У них нет ведь флага ITEM_MISSION.

**Comment by Kor-Angar** [comment]
о.. это значит просто у Лютеро инвентарь не чистится :-)

**Comment by dosinabox** [comment]
исправлено

**Comment by Kor-Angar** [comment]
Если это просто исправить это повлияет на баланс так как книги стоят по 5000 каждая, т.е. 10000 за две. И для Готики 2 это серъезная сумма. Точнее очень серъезная для первых глав. Соответственно или это не надо править или тогда делать возможность что бы эти книги не пропадали10:13, 31 июля 2020 г., dosinabox <notifications@github.com>:
исправлено

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
тогда отменю это изменение и оставлю как есть)

**Comment by Kor-Angar** [comment]
А тогда через него можно бесконечно деньги генерить. Так как у него инвентарь не чистится 😀10:20, 31 июля 2020 г., dosinabox <notifications@github.com>:
тогда отменю это изменение и оставлю как есть)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
> А тогда через него можно бесконечно деньги генерить. Так как у него инвентарь не чистится 😀

Ну и ладно. Этот проект не об этом.

**Comment by Kor-Angar** [comment]
а можно например сделать проверку на то есть ли у Лютеро книги 'Южное искусство обороны' и 'Двойные блоки'.

если книги есть у него, то инвентарь не очищать. если же у него книг нет, то очищать.

**Comment by dosinabox** [comment]
можно

**Comment by Kor-Angar** [comment]
давай попробуем такую штуку у Лютеро. Таким образом мы сможем:

- сохранить возможность отобрать книги у Лютеро (а они дико дорогие, в Готике 2 классик мало золото)
- книги Лютеро можно будет отобрать только у Лютеро, у других торговцев они будут пропадать после избиения
- через Лютеро нельзя будет майнить бесконечное золотое

**Comment by dosinabox** [comment]
> * через Лютеро нельзя будет майнить бесконечное золото

Почему? Пока книги есть, инвентарь не очищается. Продали - побили - забрали - продали.

**Comment by dosinabox** [comment]
> > * через Лютеро нельзя будет майнить бесконечное золото
> 
> Почему? Пока книги есть, инвентарь не очищается. Продали - побили - забрали проданное (не трогая книги) - продали.

**Comment by Kor-Angar** [comment]
> Почему? Пока книги есть, инвентарь не очищается. Продали - побили - забрали проданное (не трогая книги) - продали заново.

так об этом надо знать  что так можно ;-)

***

может Лютеро:
1) очищать инвентарь не удаляя при этом книги, 
2) книги удалять, если герой их прочитал

**Comment by Kor-Angar** [comment]
у Сайфера инвентарь не чистится

**Comment by Kor-Angar** [comment]
у Сайфера инвентарь не чистится


![20210301074100_1](https://user-images.githubusercontent.com/49514764/109472105-c25acd80-7a82-11eb-8b08-94a4a98e91f5.jpg)
