### ISSUE TITLE
разница между Миненталем оригинала и аддона

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#49]
- [ ] кровать в гильдии магов

**Comment by Kor-Angar** [comment]
> К сожалению, Рудниковые долины в классике и аддоне различаются, поэтому исправленный мир из обновления Г2НВ сюда не подойдет, как и Wasteland. Только если кто-нибудь не перечислит каждое отличие, чтобы я могла подстроить исправленный мир из аддона в классику.



сильно отличаются в плане перманентной травы.  это пожалуй самое трудозатратное будет

классик | нв
-- | --
![image](https://user-images.githubusercontent.com/49514764/129052338-f120409a-ac57-47b3-b4ea-42aa91838cb6.png) | ![image](https://user-images.githubusercontent.com/49514764/129052360-a86c6523-b198-4c30-952d-ce7f407e49b7.png)
https://steamcommunity.com/sharedfiles/filedetails/?id=2391494484| https://steamcommunity.com/sharedfiles/filedetails/?id=2382991833

еще есть пару перманентных зелий.

> Конкретно ландшафтных различий - я не увидел никаких.

в аддоне добавлено пару мест куда может залезть герой. что скорее хорошо, чем плохо.

***

а есть вообще смысл переносить этот мир?  какую эту задачу может решить?

**Comment by dosinabox** [comment]
> а есть вообще смысл переносить этот мир? какую эту задачу может решить?

Исправления кривых текстур, торчащих и висящих моделей, неработающих эффектов, недоступных предметов, сломанных замков, неправильного освещения.

**Comment by dosinabox** [comment]
> а если попробовать вставить траву через скрипты? или она повиснет в воздухе?

Точек для этого нет. Тут только через спейсер. Ничего сложного, но нужно знать что и куда.

**Comment by dosinabox** [comment]
Ещё отличия: алтари Белиара в аддоне.
