### ISSUE TITLE
Оригинальный FIGHT.DAT

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2_classic#5]
Требуется файл FIGHT.DAT из чистой оригинальной Г2 без аддона.

**Comment by Kor-Angar** [comment]
У меня их много. Из немецкой версии? Или Акеллы?

**Comment by dosinabox** [comment]
Без разницы, но наверное лучше от Акеллы. И чтобы точно от 1.3.

**Comment by Kor-Angar** [comment]
https://yadi.sk/d/2IzLGEz_-DF3jg
