### ISSUE TITLE
Корнелиус остался на работе

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#50]
после того как отдал дневник Корнелиуса Лорду Хагену, Корнелиус остался на своём рабочем месте
![image](https://user-images.githubusercontent.com/49514764/87882781-391eeb00-ca0b-11ea-972d-16eeb65a3cda.png)
![image](https://user-images.githubusercontent.com/49514764/87882785-40de8f80-ca0b-11ea-946f-388b9c8592d2.png)

**Comment by dosinabox** [comment]
исправлено
