### ISSUE TITLE
Уникальная одежда

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2_classic#53]
- [ ] одежда Лариуса (?)
- [ ] одежда Онара (?)
- [ ] мантия черного мага (?)

**Comment by Kor-Angar** [comment]
а в чём сабж? добавить уникальную одежду?

**Comment by dosinabox** [comment]
Да, как в обновлении Г2НВ.

**Comment by dosinabox** [comment]
добавлено всем
