### ISSUE TITLE
бонус Меча Альрика

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#61]
Меч Альрика это единственный в Готике 2 классик меч дающий бонус к навыку. этот бонус нигде не прописан и меч по задумке ничем не отличается от обычного.

при получение бонуса от меча альрика, может поменять стойка с новичка на боец или с бойца на мастре. при этом при снятие меча стойка обратно не меняется.

**Comment by dosinabox** [comment]
А у самого Альрика меняется стойка при получении этого меча? А в НВ?
