### ISSUE TITLE
Послушник / Маг Огня

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#64]
```b_startotherroutine(agon,"StillAlive");```

можно менять расписание Агону в Диалоге  с Пирокаром 
func void dia_pyrokar_oath_info()

на тот случай если герой вступить в Маги Огня не в первой главе.

***

**Comment by Kor-Angar** [comment]
вот тут лучше явно прописать мага огня и послушника

```
		if((hero.guild == GIL_MIL) || (hero.guild == GIL_PAL))
		{
			Wld_InsertItem(itam_dex_01,"FP_ROAM_XARDAS_SECRET_26");
		}
		else if((hero.guild == GIL_SLD) || (hero.guild == GIL_DJG))
		{
			Wld_InsertItem(itam_hp_01,"FP_ROAM_XARDAS_SECRET_26");
		}
		else
		{
			Wld_InsertItem(itam_hp_mana_01,"FP_ROAM_XARDAS_SECRET_26");
		};
```

а амулет жизни сделать прочим (наёмник , нейтрал,  онд)

**Comment by Kor-Angar** [comment]
это потому что явная точка в таверне не указана? :-)

![20210302103937_1](https://user-images.githubusercontent.com/49514764/109614471-bc78f100-7b43-11eb-869c-53f5dd0b7cc1.jpg)

а я то удивлялся куда он пропадал :-) а он оказывается просто не мог понять где ему тусить :-)

**Comment by dosinabox** [comment]
> на тот случай если герой вступить в Маги Огня не в первой главе.

В классике возможна такая ситуация?

> это потому что явная точка в таверне не указана? :-)

Да, нужно TAVERNE.

**Comment by Kor-Angar** [comment]
> В классике возможна такая ситуация?

да. на диалог с Хагеным нет ограничения на гильдию. поэтому и нейтрал может прейти во вторую главу и послушник

**Comment by dosinabox** [comment]
> можно менять расписание Агону в Диалоге с Пирокаром

А где оно меняется сейчас?

**Comment by Kor-Angar** [comment]
> А где оно меняется сейчас?

в b_enter_newworld_kapitel_2

**Comment by Kor-Angar** [comment]
а это что такое?:-)

```D
	KDF_AUFNAHME = LOG_SUCCESS;
	SLD_AUFNAHME = LOG_OBSOLETE;
	MIL_AUFNAHME = LOG_OBSOLETE;
```

**Comment by Kor-Angar** [comment]
и на этот диалог снять проверку на главу, что бы Маг может высказать пожелание, если стал магом во второй главе.

```D
instance DIA_PYROKAR_WUNSCH(C_INFO)
{
	npc = kdf_500_pyrokar;
	nr = 2;
	condition = dia_pyrokar_wunsch_condition;
	information = dia_pyrokar_wunsch_info;
	permanent = FALSE;
	description = "Я хотел бы высказать пожелание...";
};


func int dia_pyrokar_wunsch_condition()
{
	if((other.guild == GIL_KDF) && (KAPITEL < 2))
	{
		return TRUE;
	};
};
```

**Comment by Kor-Angar** [comment]
в **b_enter_newworld_kapitel_3**

добавить проверку на послушника.

**Comment by Kor-Angar** [comment]
ты напиши, если что то планируешь править. я это сразу проверю. у меня послушник как раз собрался в маги вступать во второй главе.

**Comment by Kor-Angar** [comment]
```D
instance DIA_MILTENOW_TEACHCIRCLE2(C_INFO)
{
	npc = pc_mage_ow;
	nr = 91;
	condition = dia_miltenow_teachcircle2_condition;
	information = dia_miltenow_teachcircle2_info;
	permanent = TRUE;
	description = "Обучи меня второму кругу магии!";
};


func int dia_miltenow_teachcircle2_condition()
{
	if((other.guild == GIL_KDF) 
	&& Npc_KnowsInfo(other,dia_miltenow_lehren) 
	&& (Npc_GetTalentSkill(other,NPC_TALENT_MAGE) < 2))
	{
		return TRUE;
	};
};
```
у мильтена или сделать как у тебя в неоф. обновление, что бы он учил и первому и второму кругу или поменять условие на (Npc_GetTalentSkill(other,NPC_TALENT_MAGE) == 1)

**Comment by dosinabox** [comment]
> а это что такое?:-)

Вступление в маги - успешно, вступление в наемники или ополчение - отменено.

> ты напиши, если что то планируешь править. я это сразу проверю. у меня послушник как раз собрался в маги вступать во второй главе.

Пока не планирую. На днях будет релиз 26 версии обновления.

Не проще ли сделать проверку на гильдию у Хагена?
Нужно ли выгонять Агона в обновлении НВ? В НВ его распорядок дня у таверны не используется.

**Comment by Kor-Angar** [comment]
> Вступление в маги - успешно, вступление в наемники или ополчение - отменено.

отмену наёмника и милицию надо делать наверное в диалоге у Педро

> Не проще ли сделать проверку на гильдию у Хагена?

неа.. изначально в самом начале  тобой этот момент прорабатывался и брались правки из мода немецкого. послушник даже руны убрали во второй главе ;-)

**Comment by Kor-Angar** [comment]
> Нужно ли выгонять Агона в обновлении НВ? В НВ его распорядок дня у таверны не используется.

старая история:-) _я предлагаю один расписать что должно происходит после испытания огнем и высказывания пожелания Пирокару._

https://github.com/dosinabox/g2nr_unofficial_update/issues/77
