### ISSUE TITLE
Корнелиуса можно обокрасть 

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#65]
Корнелиуса можно обокрасть во второй главе и украсть у него квестовую книгу из 3 главы.

![20210302120702_1](https://user-images.githubusercontent.com/49514764/109671324-06ce9200-7b85-11eb-9302-a50475b99d8e.jpg)

**Comment by Kor-Angar** [comment]
> проверить посадку Корнелиуса

сидит
![Uploading 20210303072504_1.jpg…]()

**Comment by dosinabox** [comment]
> Корнелиуса можно обокрасть во второй главе и украсть у него квестовую книгу из 3 главы.

исправлено
