### ISSUE TITLE
instance DIA_ULF_ABRECHNUNG

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#67]
в instance DIA_ULF_ABRECHNUNG(C_INFO) у Ульфа по хорошему надо 	приоритет поднять nr = 1;

***

в своей версии я ещё и проверку дополнительную повесил на всякий случай :-)

```D
instance DIA_ULF_SUCHE(C_INFO)
{
	npc = nov_602_ulf;
	nr = 9;
	condition = dia_ulf_suche_condition;
	information = dia_ulf_suche_info;
	permanent = FALSE;
	important = TRUE;
};


func int dia_ulf_suche_condition()
{
	if	Npc_KnowsInfo(hero,DIA_ULF_ABRECHNUNG)
	{
		return false;
	};

	if((MIS_SCHNITZELJAGD == LOG_RUNNING) && (other.guild == GIL_NOV) && (Npc_GetDistToWP(self,"NW_TROLLAREA_PATH_42") <= 1000))
	{
		return TRUE;
	};
};

```

**Comment by Kor-Angar** [comment]
халтура :-))


```D
func int dia_ulf_hallo_condition()
{
	if((hero.guild != GIL_NOV) && (hero.guild != GIL_KDF) && (MIS_SCHNITZELJAGD == FALSE))
	{
		return TRUE;
	};
};

func void dia_ulf_hallo_info()
{
	AI_Output(other,self,"DIA_Ulf_Hallo_15_00");	//Что ты делаешь здесь?
	if(hero.guild == GIL_KDF)
	{
		AI_Output(self,other,"DIA_Ulf_Hallo_03_01");	//Если тебе интересно это знать, я выполняю задание монастыря.
	}
```

можешь в копилку неиспользуемых реплик добавить :-)
		AI_Output(self,other,"DIA_Ulf_Hallo_03_01");	//Если тебе интересно это знать, я выполняю задание монастыря.

**Comment by Kor-Angar** [comment]
> в instance DIA_ULF_ABRECHNUNG(C_INFO) у Ульфа по хорошему надо приоритет поднять nr = 1;

что бы при первой встречи, если герой уже нашёл руну был разговор адекватный :-)

https://www.youtube.com/watch?v=m0K7k_I2aJY

**Comment by dosinabox** [comment]
> можешь в копилку неиспользуемых реплик добавить :-)

Добавлю. В обновлении уже было исправлено.


> в instance DIA_ULF_ABRECHNUNG(C_INFO) у Ульфа по хорошему надо приоритет поднять nr = 1;

готово
