### ISSUE TITLE
Оригинальные GothicGame.ini и GothicGame.rtf

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g2_classic#7]
Требуются файлы GothicGame.ini и GothicGame.rtf из папки system чистого оригинала от Акеллы 1.3 без аддона.

**Comment by Kor-Angar** [comment]
Game.ini
[Gothic.zip](https://github.com/dosinabox/g2_classic/files/3581310/Gothic.zip)

**Comment by Kor-Angar** [comment]
> Требуются файлы GothicGame.ini и GothicGame.rtf из папки system чистого оригинала от Акеллы 1.3 без аддона.

нет таких
![image](https://user-images.githubusercontent.com/49514764/64383400-71f5e180-d03e-11e9-98f4-75bb4e34478a.png)

**Comment by dosinabox** [comment]
Нужно поставить мод-стартер для 1.3, если такой вообще существует. Да ещё и на русском.

**Comment by dosinabox** [comment]
Вопрос неактуален. Всё нашлось.
