### ISSUE TITLE
Лестер идет в Башню Ксардаса

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#8]
Если поговорить с Лестером после посещения города в 1или 2 главе, то Лестер не идет к Ксардасу. Соотвеьсвенно Ксардас не рассказываеь про Ищущих, не дает опыт и Кольцо.

**Comment by dosinabox** [comment]
А мы что, будем править баги и косяки оригинала?

**Comment by Kor-Angar** [comment]
не знаю:-) что вижу то пишу

**Comment by dosinabox** [comment]
Пиши) Но исправлять буду только самое простое, потому что нет времени. И вообще, уже ведь есть мод-фикс для классики. Проще будет в нем поправить баланс, чем делать с нуля новый проект уровня неофициального обновления г2нв с многолетней разработкой. Не подпишусь!

**Comment by dosinabox** [comment]
Сейчас мне хотелось бы удовлетворить спрос на чистый оригинал на движке 2.6, в частности, для стим-версии. Или если не полностью чистый, то с самыми минимальными правками. Такой спрос есть. А исправленный и допиленный оригинал без аддона уже существует, его я тоже буду продвигать, чтобы у людей был выбор.

**Comment by Kor-Angar** [comment]
Я не думаю что можно Оригинал так же править  как НВ. В частности много правок в НВ из-за того что он стыковался с оригиналом, пеработанный баланс и т.д.

А в целом твой полностью поддерживаю 🙂

**Comment by dosinabox** [comment]
Да, скорее всего будет отдельным модом.
