### ISSUE TITLE
Офф Топ

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#9]
Что то не смог тег поставить

**Comment by dosinabox** [comment]
выпущена версия 0.4

**Comment by dosinabox** [comment]
Какое-то время поиграй с генерацией логов zSpy, пожалуйста. Может, что-то новое вылезет. У Г2НВ уже всё нормально, но потом тоже надо будет, когда начнешь на новой тестовой сборке обновления. Сообщи когда запланируешь новое прохождение с аддоном.

**Comment by dosinabox** [comment]
выпущена версия 0.5

**Comment by dosinabox** [comment]
В Г2 посох судьи - одноручный)

**Comment by dosinabox** [comment]
выпущена версия 0.6

**Comment by Kor-Angar** [comment]
> В Г2 посох судьи - одноручный)

это как?

**Comment by Kor-Angar** [comment]
![image](https://user-images.githubusercontent.com/49514764/64929064-b1d07c00-d829-11e9-9de3-8951914a70c8.png)
110 радиус :-))

**Comment by dosinabox** [comment]
> это как?

А вот так:
![1r](https://user-images.githubusercontent.com/39790055/65080512-26cabf80-d9aa-11e9-8a9e-6f66fb547b04.jpg)
![2р](https://user-images.githubusercontent.com/39790055/65080513-26cabf80-d9aa-11e9-8d54-571d6efa84d2.jpg)

**Comment by dosinabox** [comment]
выпущена версия 0.7

**Comment by dosinabox** [comment]
Мод предварительно ушел в массы и добавлен в руководство для стим-версии Г2НВ:
https://steamcommunity.com/sharedfiles/filedetails/?id=787949644

**Comment by dosinabox** [comment]
выпущена версия 0.8

**Comment by dosinabox** [comment]
выпущена версия 0.9

**Comment by dosinabox** [comment]
релиз на wop:
https://worldofplayers.ru/threads/41796

**Comment by Kor-Angar** [comment]
Там по тексту было бы здорово продублировать ссылку на g2_classic_v0.9_install.exe17:15, 18 января 2020 г., dosinabox <notifications@github.com>:релиз на wop:
https://worldofplayers.ru/threads/41796

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
это как?

**Comment by Kor-Angar** [comment]
g2_classic_v0.9_install.exe  уже кликабельна. наверное и g2classic_russian.vdf тоже надо сделать кликабельной

***

Установка:
Для Steam: скопировать файл g2classic_russian.vdf из архива в папку Gothic II/Data, запустить игру через Steam и начать новую игру.
Для прочих версий:
- установить Report версию 2.6.0.0-rev2 (fix)
- установить Gothic2_PlayerKit-2.8
- запустить установщик g2_classic_v0.9_install.exe и следовать его инструкциям
- запуск мода производится через стартер модов GothicStarter.exe

**Comment by Kor-Angar** [comment]
пытаюсь запустить Готику 2 классик, выдаёт вот такое и вылетает.
 
![image](https://user-images.githubusercontent.com/49514764/76292712-bfd6f500-62c0-11ea-8797-614b55e2563a.png)

какие есть варианты починки? :-) удалить и заново поставить?

**Comment by dosinabox** [comment]
Откуда запускается?

**Comment by Kor-Angar** [comment]
starter
![image](https://user-images.githubusercontent.com/49514764/76294967-e139e000-62c4-11ea-8725-d1385e5c6810.png)

**Comment by dosinabox** [comment]
GothicStarter_mod.exe - только для модостроителей, там все предупреждения и сообщения превращаются в ошибки и сразу вываливаются для отлова. Кажется, уже говорила. Используй вместо него GothicStarter.exe.

**Comment by Kor-Angar** [comment]
тоже самое. вылетает с ошибкой
![image](https://user-images.githubusercontent.com/49514764/76295370-8d7bc680-62c5-11ea-8ddc-d4fdc618ddb6.png)

**Comment by dosinabox** [comment]
покажи что в папках Data и Data/ModVDF

**Comment by Kor-Angar** [comment]
а модфикс запустился

**Comment by Kor-Angar** [comment]
> покажи что в папках Data и Data/ModVDF

разобрался. удалил файл g2_classic_hotfix и и всё заработало

**Comment by dosinabox** [comment]
а версия сейчас 0.9?

**Comment by dosinabox** [comment]
выпущена версия 1.0

**Comment by dosinabox** [comment]
Готова версия 1.1, но я не выпущу её раньше августа-сентября, когда выйдет 25 версия обновления г2нв. Если захочешь поиграть, то выложу тебе для тестирования.

**Comment by Kor-Angar** [comment]
Выложи. Только как мод версию. 10:06, 6 июля 2020 г., dosinabox <notifications@github.com>:
Готова версия 1.1, но я не выпущу её раньше августа-сентября, когда выйдет 25 версия обновления г2нв. Если захочешь поиграть, то выложу тебе для тестирования.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by dosinabox** [comment]
https://dropmefiles.com/ihmdx

**Comment by dosinabox** [comment]
выпущена версия 1.1

**Comment by Kor-Angar** [comment]
удалил мод. установил заново. запустил игру:
меню из НВ
![image](https://user-images.githubusercontent.com/49514764/93693039-36bc3880-fb03-11ea-9d75-fb9c3808a854.png)
диалоги ксардаса норм, но возле него лежала табличка
![image](https://user-images.githubusercontent.com/49514764/93693043-4471be00-fb03-11ea-89d1-a12f0db3394c.png)

**Comment by dosinabox** [comment]
Скриншот файлов в папках Data и Data/ModVDF с датами их модификаций - в студию.

**Comment by Kor-Angar** [comment]
> Скриншот файлов в папках Data и Data/ModVDF с датами их модификаций - в студию.

спорить не буду
![image](https://user-images.githubusercontent.com/49514764/93705257-66c80380-fb24-11ea-9d6b-af28f3e3226e.png)
![image](https://user-images.githubusercontent.com/49514764/93705260-6af42100-fb24-11ea-8608-22f7ad23f9db.png)


мне кажется дело в  ini файле
> [INFO]
> Title=\'c3\'ee\'f2\'e8\'ea\'e0 2: \'ca\'eb\'e0\'f1\'f1\'e8\'f7\'e5\'f1\'ea\'e0\'ff
> Version=1.1
> Authors=D36, Kor Angar
> Webpage=http://worldofplayers.ru/threads/41796
> Description=!<symlink>g2_classic.rtf
> Icon=g2_classic.ico
> 
> [FILES]
> VDF=g2_classic.mod  g2_classic_hotfix.mod  g2a_nr_scriptpatch_v23.mod  g2a_nr_scriptpatch_v24.mod  g2a_nr_scriptpatch_v25.mod

**Comment by dosinabox** [comment]
```
VDF=g2_classic.mod
```
Что изменится, если убрать из этой строки всё, кроме этого модуля?

**Comment by dosinabox** [comment]
Какой timestamp у g2a_nr_scriptpatch_v25.mod?

**Comment by dosinabox** [comment]
Через что запускаешь? GothicStarter_mod.exe?

**Comment by Kor-Angar** [comment]
> Что изменится, если убрать из этой строки всё, кроме этого модуля?

так работает всё нормально
```
VDF=g2_classic.mod  g2_classic_hotfix.mod
;VDF=g2_classic.mod  g2_classic_hotfix.mod  g2a_nr_scriptpatch_v23.mod  g2a_nr_scriptpatch_v24.mod  g2a_nr_scriptpatch_v25.mod
```

> Какой timestamp у g2a_nr_scriptpatch_v25.mod?

не знаю что такое _timestamp_

> Через что запускаешь? GothicStarter_mod.exe?

да

**Comment by dosinabox** [comment]
> не знаю что такое _timestamp_

![image](https://user-images.githubusercontent.com/39790055/93705733-397d5480-fb28-11ea-8da1-3e3b9c5e99e9.png)

**Comment by dosinabox** [comment]
> да

С какими параметрами?
И в очередной раз говорю, чтобы ты его не использовал)

**Comment by Kor-Angar** [comment]
> И в очередной раз говорю, чтобы ты его не использовал)

а у меня с ним игра корректно работает. а без него не корректно ;-)

> timestamp

![image](https://user-images.githubusercontent.com/49514764/93705832-5b2b0b80-fb29-11ea-9dce-1d977ee1a809.png)

**Comment by dosinabox** [comment]
> без него не корректно

это как?

**Comment by Kor-Angar** [comment]
это при игре с D3D11  без галки "запускать в окне" герой когда бежит пробуксовывает.

**Comment by dosinabox** [comment]
> это при игре с D3D11 без галки "запускать в окне" герой когда бежит пробуксовывает.

Так это zStartupWindowed=1 в Gothic.ini или BorderlessWindow=1 в SystemPack.ini. И стартер для разработчиков для этого не нужен)


А если сделать так?
```
VDF=g2a_nr_scriptpatch_v23.mod  g2a_nr_scriptpatch_v24.mod  g2a_nr_scriptpatch_v25.mod  g2_classic.mod  g2_classic_hotfix.mod
```

**Comment by Kor-Angar** [comment]
>  И стартер для разработчиков для этого не нужен)

без этого стартера так же и  zspy не пишет ошибки. у меня сейчас Ночь Ворона вылетает при заходе в рудниковую долину, а отчего я не знаю, так как играл через твой стартер.

**Comment by Kor-Angar** [comment]
тоже актуально в Классике
https://github.com/dosinabox/g2nr_unofficial_update/issues/277

**Comment by dosinabox** [comment]
выпущена версия 1.2

**Comment by Kor-Angar** [comment]
я наверное классику пройду. есть какие то пожелания, рекомендации, задания? :-)

**Comment by dosinabox** [comment]
хм, вроде ничего особенного не требуется
- проверить рога мракорисов у Бастера
- проверить посадку Корнелиуса
- поглядывать в книгу статистики, всё ли правильно считается
- обратить внимание на драконов, ничего ли не сломалось

**Comment by dosinabox** [comment]
> пожелания, рекомендации, задания?

Закрыть/проверить эти вопросы:
https://github.com/dosinabox/g2_classic/issues/4
https://github.com/dosinabox/g2_classic/issues/32

**Comment by dosinabox** [comment]
Маленький бонус, сделанный за вечер: исправленные русские скрипты 1.30, адаптированные под движок 2.6, подогнанные под английскую демо-версию 1.28. Получаем демо классики Г2 на русском языке на движке 2.6. Интересно с исторической точки зрения) Или посмотреть, что можно из нее выжать, до какого уровня докачаться и т.д.
[g2_demo.zip](https://github.com/dosinabox/g2_classic/files/6022297/g2_demo.zip)

**Comment by Kor-Angar** [comment]
а как то инсталлер мне не предложил поставить игру в стим папку с Готикой 2 :-)

**Comment by Kor-Angar** [comment]
можно продублировать  книгу  в инстастанции тестого амулета.

так же добавить вызов книги помощнику

**Comment by Kor-Angar** [comment]
можно добавить визуальный эффект магичиским свиткам / амулетам / зельям

**Comment by Kor-Angar** [comment]
оказалось что ловкость за молитвы может выпасть только у Пала :-) 

```D
else if(SpecialBless <= 10)
	{
		if(hero.guild == GIL_PAL)
		{
			if(zufall >= 3)
			{
				B_BlessAttribute(hero,ATR_MANA_MAX,4);
			}
			else if(zufall >= 2)
			{
				B_BlessAttribute(hero,ATR_HITPOINTS_MAX,8);
			}
			else if(zufall >= 1)
			{
				B_BlessAttribute(hero,ATR_STRENGTH,2);
			}
			else if(zufall >= 0)
			{
				B_BlessAttribute(hero,ATR_DEXTERITY,2);
			};
		}
		else if(hero.guild == GIL_KDF)
		{
			B_BlessAttribute(hero,ATR_MANA_MAX,4);
		}
		else if(zufall >= 2)
		{
			B_BlessAttribute(hero,ATR_HITPOINTS_MAX,4);
		}
		else
		{
			B_BlessAttribute(hero,ATR_STRENGTH,1);
		};
		SpecialBless = SpecialBless + 1;
	}
```
в веб архиве тоже пишут что ловкости нет
![image](https://user-images.githubusercontent.com/49514764/109429297-23938a00-7a0c-11eb-9515-d924c586b533.png)

***

но при этом пишут почему то про главы :-)

else if(SpecialBless <= 10)  // получается что бонусов не 10, а  11 ? :-)

**Comment by Kor-Angar** [comment]
> 		CreateInvItems(lester,itmw_1h_bau_axe,1);

это как? :-)

**Comment by dosinabox** [comment]
b_enter_newworld_kapitel_3()? Совершенно не представляю, зачем это здесь нужно)

**Comment by Kor-Angar** [comment]
может быть в ранних версиях Лестер был смертным :-)

**Comment by Kor-Angar** [comment]
пираньи конечно молодцы
в Готике 2 классик герой имея 230 ловкости в 4 главе из Лука убивает человека ящера с одного выстрела
в Готике 2 НВ  герой имея 230 ловкости в 4 главе из Лука убивает человека ящера с одного выстрела

при этом баланс совсем разный, параметры разные и даже луки разные, так в НВ в 4 главе герой может использовать ItRw_Bow_H_04, а в Готике 2 классик лишь ItRw_Bow_H_02. а цифра 230 одинаковая :-)

**Comment by Kor-Angar** [comment]
я бы взялся за правки Готики 2 классик, но не хочется плодить множества :-) проекты и сборки :-)

Лестер в 3 главе сидит в долине :-(

**Comment by Kor-Angar** [comment]
а почему телепорты в оригинальном коде не сработали?

```D
	b_startotherroutine(marcos_guard1,"MARCOS");
	b_startotherroutine(marcos_guard2,"MARCOS");
	AI_Teleport(marcos_guard1,"OW_STAND_GUARDS");
	AI_Teleport(marcos_guard1,"OW_STAND_GUARDS");
```
![20210308184046_1](https://user-images.githubusercontent.com/49514764/110367284-86160700-8058-11eb-96c2-1f90cf195ff3.jpg)

**Comment by Kor-Angar** [comment]
а ты мир редактировала?

**Comment by dosinabox** [comment]
нет

**Comment by dosinabox** [comment]
хотя в версии 1.2 был добавлен файл Ирдората из неофициального обновления
остальные миры без изменений
