### ISSUE TITLE
реплики на польском

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g2_classic#98]
не было реплик на польском про то что не хватает очков обучения

`$NOLEARNNOPOINTS`

**Comment by dosinabox** [comment]
В какой диалоге не было этой реплики?

**Comment by Kor-Angar** [comment]
наверное я просто перепутал. думал что говорят на польском языке, а сейчас запустил там весь звук немецкий и все реплики на немецком из томов игры. извини за дезинформацию :-)
